version: 2.1

jobs:
  build: 
    docker:
      - image: circleci/node:10.0-browsers
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - set-env
      - run:
          name: "What branch am I on?"
          command: echo ${CIRCLE_BRANCH}
      - run:
          name: "What was my custom environment variable?"
          command: echo ${MY_ENV_VAR}

commands:
  set-env:
    steps:           
      - run:
          name: "set env var"
          command: echo 'export MY_ENV_VAR="FOO"' >> $BASH_ENV

workflows:
  build:
    jobs:
      - build
